'use client';
import { useState, useRef } from 'react';
import { Upload, Check, FileSpreadsheet, Files, ArrowRight, Download, LoaderCircle, ShieldCheck, Plus, CalendarDays } from 'lucide-react';
import { SOURCES, CATEGORY_LABEL, CATEGORIES, type State, type Source, type Category } from '@/lib/model';
import { fmt } from '@/lib/domain';
import { extractPDF } from '@/lib/pdf-client';
import { Modal, type Act } from './shared';
export default function Importer({state,act,reload,onReview,notify}:{state:State;act:Act;reload:()=>Promise<void>;onReview:()=>void;notify:(s:string)=>void}) {
  const [source,setSource]=useState<Source>('history'),[busy,setBusy]=useState(''),[confirm,setConfirm]=useState(false),[checked,setChecked]=useState(false),[opening,setOpening]=useState<Category|null>(null),[localError,setLocalError]=useState('');
  const input=useRef<HTMLInputElement>(null);
  const required=SOURCES.filter(s=>s.required),ready=required.filter(s=>state.documents.some(d=>d.source===s.key)||state.unavailable[s.key]).length;
  async function upload(files:FileList|null) {
    if(!files?.length)return;setLocalError('');
    try {for(const file of Array.from(files)) {
      if(file.size>3*1024*1024)throw new Error(`${file.name}: o limite é de 3 MB por arquivo. Divida arquivos maiores.`);
      setBusy(`Analisando ${file.name}…`);const form=new FormData();form.set('file',file);form.set('source',source);
      if(/\.pdf$/i.test(file.name))form.set('pages',JSON.stringify(await extractPDF(file,setBusy)));
      const r=await fetch('/api/import',{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.error);
      notify(data.duplicate?`${file.name} já foi recebido. Nenhum registro duplicado.`:`${file.name}: ${data.count} registros recebidos para análise.`);
    }}catch(e){setLocalError((e as Error).message);}finally{setBusy('');await reload();if(input.current)input.current.value='';}
  }
  function template(products=false) {
    const text=products?'SKU;Nome do produto;Categoria;Peso unitário g\n':'Data;Invoice;Pedido;Cliente;Destinatário;Estado;SKU;Nome do produto;Categoria;Quantidade;Peso unitário g;KG;Transporte;Cargo/Courier;Origem\n';
    const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));a.download=products?'modelo-produtos.csv':'modelo-movimentacoes.csv';a.click();URL.revokeObjectURL(a.href);
  }
  return <>
    <div className="steps"><div className="active"><span>1</span> Reunir arquivos</div><i/><div><span>2</span> Conferir e conciliar</div><i/><div><span>3</span> Consultar relatórios</div></div>
    <div className="import-layout"><section className="panel upload-panel"><div className="panel-heading"><div><span className="eyebrow">COMECE POR AQUI</span><h2>Seus arquivos, em um só lugar.</h2><p>Selecione a origem e envie os documentos para análise.</p></div><span className="large-icon"><Files size={26}/></span></div>
      <label className="field-label" htmlFor="source">Qual é a origem destes arquivos?</label><select id="source" value={source} onChange={e=>setSource(e.target.value as Source)} disabled={!!busy}>{SOURCES.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select>
      <div className={'drop-zone '+(busy?'processing':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void upload(e.dataTransfer.files);}}><span className="upload-icon">{busy?<LoaderCircle className="spin" size={27}/>:<Upload size={27}/>}</span><h3>{busy||'Arraste seus arquivos até aqui'}</h3><p>{busy?'Os documentos originais serão preservados.':'XLSX, CSV ou PDF · até 3 MB por arquivo'}</p><button className="primary" disabled={!!busy} onClick={()=>input.current?.click()}><Plus size={17}/> Selecionar arquivos</button><input ref={input} type="file" multiple accept=".xlsx,.csv,.pdf" hidden onChange={e=>void upload(e.target.files)}/></div>
      {localError&&<div role="alert" className="error-box">{localError}</div>}
      <div className="subtle-note"><ShieldCheck size={19}/><span>Seu histórico é preservado. Arquivos repetidos são identificados antes de criar novos registros.</span></div>
      <div className="template-links"><button className="text-link" onClick={()=>template()}><Download size={15}/> Modelo de movimentações</button><button className="text-link" onClick={()=>template(true)}><Download size={15}/> Modelo de produtos</button></div>
    </section>
    <section className="panel checklist"><div className="section-heading"><h2>Checklist de importação</h2><span className="counter">{ready}/{required.length}</span></div><div className="progress"><span style={{width:`${ready/required.length*100}%`}}/></div><p className="muted">Envie agora ou indique o que não está disponível.</p>
      {SOURCES.map(s=>{const docs=state.documents.filter(d=>d.source===s.key),missing=state.unavailable[s.key];return <div className="checklist-row" key={s.key}><span className={'check-circle '+(docs.length?'done':missing?'skipped':'')}>{docs.length?<Check size={14}/>:missing?'−':null}</span><div><strong>{s.label}{!s.required&&<small>Opcional</small>}</strong>{docs.length?<small className="success">{docs.length} arquivo{docs.length>1?'s':''} recebido{docs.length>1?'s':''}</small>:<label className="check-label"><input type="checkbox" checked={!!missing} onChange={e=>void act({action:'checklist',unavailable:{...state.unavailable,[s.key]:e.target.checked}})}/> Arquivo não disponível</label>}</div><button className="icon-button" aria-label={`Enviar ${s.label}`} onClick={()=>{setSource(s.key);input.current?.click();}}><Upload size={16}/></button></div>;})}
    </section></div>
    <section className="panel opening-section"><div><span className="eyebrow">PONTO DE PARTIDA</span><h2>Estoque inicial</h2><p>Informe o saldo no início da data de referência, antes das movimentações desse dia.</p></div><div className="opening-cards">{CATEGORIES.map(cat=>{const m=state.movements.find(m=>m.category===cat&&m.kind==='OPENING_STOCK'&&m.status!=='ignored');return <div className="opening-card" key={cat}><span className={'product-dot '+cat}/><div><strong>{CATEGORY_LABEL[cat]}</strong><p>{m?`${fmt(m.kg)} KG · ${m.date.split('-').reverse().join('/')}`:'Ainda não informado'}</p></div>{m?.historical?<span className="badge neutral">Histórico aceito</span>:<button className="text-link" onClick={()=>m?onReview():setOpening(cat)}>{m?'Revisar':'Informar'}</button>}</div>;})}</div></section>
    {!!state.documents.length&&<section className="panel"><div className="section-heading"><h2>Arquivos recebidos</h2><span className="muted">{state.documents.length} documentos preservados</span></div><div className="table-scroll"><table><thead><tr><th>Arquivo</th><th>Fonte</th><th>Análise</th><th>Recebido em</th><th>Original</th></tr></thead><tbody>{state.documents.map(d=><tr key={d.id}><td><span className="file-name"><FileSpreadsheet size={17}/>{d.name}</span></td><td>{SOURCES.find(s=>s.key===d.source)?.label}</td><td>{d.sheets.length?<details><summary>{d.sheets.length} abas analisadas</summary>{d.sheets.map(s=><p key={s.name}>{s.name}: {s.rows} linhas. {s.treatment}</p>)}</details>:d.extraction}</td><td>{new Date(d.importedAt).toLocaleDateString('pt-BR')}</td><td><a className="text-link" href={`/api/documents/${d.id}`}>Baixar</a></td></tr>)}</tbody></table></div></section>}
    <div className="import-footer"><div><strong>{state.movements.filter(m=>m.status==='staged').length} registros aguardando processamento</strong><p>Arquivos ausentes e pendências serão indicados nos relatórios.</p></div><button className="primary" disabled={!!busy||ready<required.length} onClick={()=>{setChecked(false);setConfirm(true);}}>Conferir checklist e continuar</button></div>
    {confirm&&<Modal title="Conferir antes de processar" onClose={()=>setConfirm(false)}><p>Confira os arquivos recebidos. Somente registros sem pendências serão contabilizados. Os demais ficarão em Revisar Dados.</p><div className="confirmation-list">{SOURCES.map(s=><div key={s.key}><span>{s.label}</span><strong>{state.documents.filter(d=>d.source===s.key).length||'Não disponível'}</strong></div>)}</div><label className="check-label important"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> Conferi o checklist e entendo que fontes ausentes geram relatórios incompletos.</label><button className="primary full" disabled={!checked} onClick={async()=>{await act({action:'commit',confirmed:true});setConfirm(false);onReview();}}>Processar dados recebidos</button></Modal>}
    {opening&&<Modal title={`Estoque inicial · ${CATEGORY_LABEL[opening]}`} onClose={()=>setOpening(null)}><form onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);await act({action:'opening',category:opening,date:data.get('date'),kg:Number(data.get('kg')),reason:data.get('reason')});setOpening(null);}}><label className="field-label">Data de referência<input name="date" type="date" required/></label><label className="field-label">Estoque em KG<input name="kg" type="number" min="0" step="any" required/></label><label className="field-label">Origem da contagem<textarea name="reason" placeholder="Ex.: contagem física realizada no fechamento do dia anterior" required/></label><p className="muted">Se a contagem foi feita ao final do dia, selecione o dia seguinte.</p><button className="primary full">Salvar estoque inicial</button></form></Modal>}
  </>;
}
