'use client';
import { useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Package, CircleAlert, FileSearch, Download, Search, SlidersHorizontal } from 'lucide-react';
import { CATEGORY_LABEL, CATEGORIES, MONTHS, KIND_LABEL, SOURCES, type State, type Movement, type Category } from '@/lib/model';
import { monthly, contributions, fmt, lb, monthlyLb, type MonthlyMetric, type Monthly } from '@/lib/domain';
import { filtered, floridaRows, type Filters } from '@/lib/reports';
import HistoricalWorkbook from './historical-workbook';
import { trustedReference } from '@/lib/historical-policy';
import { Empty, Modal, MovementRows } from './shared';
export function Dashboard({state,year,onImport,onReview}:{state:State;year:number;onImport:()=>void;onReview:()=>void}) {
  const [month,setMonth]=useState('10');const [detail,setDetail]=useState<{cat:Category;metric:keyof Monthly;month:string}|null>(null);
  const pending=state.movements.filter(m=>['pending','staged'].includes(m.status)).length;
  return <><div className="dashboard-toolbar"><p>Posição no fechamento do mês selecionado</p><select aria-label="Mês do dashboard" value={month} onChange={e=>setMonth(e.target.value)}>{MONTHS.map((m,i)=><option key={m} value={String(i+1).padStart(2,'0')}>{m} {year}</option>)}</select></div><div className="stock-grid">{CATEGORIES.map(cat=>{const rows=monthly(state,cat,year),r=rows[Number(month)-1],has=state.movements.some(m=>m.category===cat&&m.status==='accepted');return <section key={cat} className={'stock-card '+cat}><div className="stock-card-head"><span className="product-label"><span className={'product-dot '+cat}/>{CATEGORY_LABEL[cat]}</span><Package size={21}/></div><span className="muted">Estoque no fechamento</span><button className="stock-value" onClick={()=>setDetail({cat,metric:'closing',month:r.month})}>{fmt(r.closing)} <small>KG</small></button><p>{r.closing===null?'Informe e confirme o estoque inicial':`${fmt(monthlyLb(r,'closing'))} LB`}</p>{r.partial&&<span className="badge pending">Mês com contagem parcial</span>}{!r.historical&&r.closing!==null&&r.closing<0&&<span className="badge pending">Estoque negativo · revisar</span>}<div className="stock-flows"><button onClick={()=>setDetail({cat,metric:'entries',month:r.month})}><ArrowDownLeft size={18}/><div><small>Entradas do mês</small><strong>{has?fmt(r.entries):'—'} KG</strong></div></button><div><ArrowUpRight size={18}/><div><small>Saídas do mês</small><strong>{has?fmt(r.wholesale+r.sites+r.losses):'—'} KG</strong></div></div></div><div className="channel-grid">{([['wholesale','Atacado'],['sites','Sites'],['losses','Perdas']] as [keyof Monthly,string][]).map(([key,label])=><button key={key} onClick={()=>setDetail({cat,metric:key,month:r.month})}><small>{label}</small><strong>{has?fmt(r[key] as number):'—'} <span>KG</span></strong></button>)}</div></section>;})}</div>
    <div className="dashboard-bottom"><section className="panel"><div className="section-heading"><div><h2>Movimentação ao longo do ano</h2><p>Entradas e saídas de Dry Snuff · KG</p></div><div className="legend"><span>Entradas</span><span>Saídas</span></div></div>{state.movements.some(m=>m.status==='accepted'&&m.category==='DRY_SNUFF'&&m.kind!=='OPENING_STOCK')?<div className="bar-chart">{monthly(state,'DRY_SNUFF',year).map((r,i,all)=>{const max=Math.max(1,...all.flatMap(x=>[x.entries,x.wholesale+x.sites+x.losses]));return <div className="bar-month" key={r.month}><div className="bars"><span title={`${fmt(r.entries)} KG entradas`} style={{height:`${r.entries/max*100}%`}}/><span title={`${fmt(r.wholesale+r.sites+r.losses)} KG saídas`} style={{height:`${(r.wholesale+r.sites+r.losses)/max*100}%`}}/></div><small>{MONTHS[i].slice(0,3)}</small></div>;})}</div>:<Empty title="Seu histórico começa com os arquivos" description="As movimentações confirmadas aparecerão aqui, mês a mês." action={<button className="secondary" onClick={onImport}>Adicionar arquivos</button>}/>}</section><section className="panel attention"><CircleAlert size={25}/><h2>Central de conferência</h2><strong className="big-number">{pending}</strong><p>registros aguardando revisão</p><div className="hairline"/><p>Classificações, documentos ausentes e possíveis duplicidades são reunidos em uma só tela.</p><button className="secondary full" onClick={onReview}>Revisar dados</button></section></div>{detail&&<Composition state={state} detail={detail} onClose={()=>setDetail(null)}/>}</>;
}
export function FilterBar({filters:f,setFilters,advanced=false}:{filters:Filters;setFilters:(f:Filters)=>void;advanced?:boolean}) {const [more,setMore]=useState(false);return <div className="filter-panel"><div className="filters"><div className="search-input"><Search size={17}/><input aria-label="Buscar cliente ou invoice" placeholder="Cliente, invoice ou pedido" value={f.search} onChange={e=>setFilters({...f,search:e.target.value})} disabled={!advanced}/></div><select aria-label="Filtrar mês" value={f.month} onChange={e=>setFilters({...f,month:e.target.value})}><option value="">Todos os meses</option>{MONTHS.map((m,i)=><option key={m} value={String(i+1).padStart(2,'0')}>{m}</option>)}</select><select aria-label="Filtrar produto" value={f.category} onChange={e=>setFilters({...f,category:e.target.value})}><option value="">Todos os produtos</option>{CATEGORIES.map(c=><option key={c} value={c}>{CATEGORY_LABEL[c]}</option>)}</select>{advanced&&<button className="secondary" onClick={()=>setMore(!more)}><SlidersHorizontal size={16}/> Filtros</button>}</div>{more&&advanced&&<div className="filters extra"><input aria-label="Estado" placeholder="Estado de entrega" value={f.state} onChange={e=>setFilters({...f,state:e.target.value})}/><select aria-label="Site" value={f.site} onChange={e=>setFilters({...f,site:e.target.value})}><option value="">Todos os sites</option>{['Sacred','Haux Haux','Natural Medicine'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Canal" value={f.kind} onChange={e=>setFilters({...f,kind:e.target.value})}><option value="">Todos os canais</option>{Object.entries(KIND_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="Origem" value={f.source} onChange={e=>setFilters({...f,source:e.target.value})}><option value="">Todas as origens</option>{SOURCES.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></div>}</div>;}
export function Ledger({state,filters,entry,onOrigin,onEdit}:{state:State;filters:Filters;entry:boolean;onOrigin:(m:Movement)=>void;onEdit:(m:Movement)=>void}) {
  const rows=filtered(state.movements.filter(m=>m.status==='accepted'&&(entry?m.kind==='ENTRY':['WHOLESALE_SALE','SITE_SALE','LOSS'].includes(m.kind))),filters);
  return <>{CATEGORIES.filter(c=>!filters.category||filters.category===c).map(cat=>{const subset=rows.filter(m=>m.category===cat);return <section className="panel" key={cat}><div className="section-heading"><h2><span className={'product-dot '+cat}/>{CATEGORY_LABEL[cat]}</h2><span className="muted">{subset.length} registros · {fmt(subset.reduce((n,m)=>n+(m.kg||0),0))} KG</span></div>{subset.length?<MovementRows rows={subset} onOrigin={onOrigin} onEdit={onEdit} entry={entry}/>:<Empty title="Nenhuma movimentação confirmada" description="Importe os documentos e resolva as pendências para preencher esta tabela."/>}</section>;})}</>;
}
function Composition({state,detail,onClose}:{state:State;detail:{cat:Category;metric:keyof Monthly;month:string};onClose:()=>void}) {const refs=state.references?.filter(r=>trustedReference(state,r)&&r.category===detail.cat&&r.month===detail.month&&r.metric===detail.metric)||[];if(refs.length)return <Modal title="Valor histórico original" onClose={onClose}><p>Aceito como está na planilha, sem correção ou conferência.</p>{refs.map(r=><p key={r.id}>{fmt(r.kg)} KG · {fmt(r.originalLb)} LB · <a href={`/api/documents/${r.documentId}`}>{r.sheet}, linha {r.row}</a></p>)}</Modal>;const rows=contributions(state,detail.cat,detail.month,detail.metric);return <Modal title={`Composição · ${CATEGORY_LABEL[detail.cat]} · ${detail.month}`} onClose={onClose} wide><p>Registros que compõem o valor selecionado. Entradas e estoque inicial somam; vendas e perdas reduzem o saldo.</p>{detail.metric==='sites'&&<div className="channel-grid">{['Sacred','Haux Haux','Natural Medicine'].map(s=><div key={s}><small>{s}</small><strong>{fmt(rows.filter(m=>m.site===s).reduce((n,m)=>n+(m.kg||0),0))} KG</strong></div>)}</div>}{rows.length?<div className="table-scroll"><table><thead><tr><th>Data</th><th>Invoice</th><th>Tipo / canal</th><th>KG</th><th>Documentos</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{m.date}</td><td>{m.invoice||m.order||'Contagem'}</td><td>{m.site||KIND_LABEL[m.kind]}</td><td>{fmt(m.kg)}</td><td>{m.origins.map((o,i)=><a key={i} className="text-link block" href={`/api/documents/${o.documentId}`}>{o.file}{o.row?` · linha ${o.row}`:''}</a>)}</td></tr>)}</tbody></table></div>:<Empty title="Nenhum lançamento compõe este valor" description="Um saldo desconhecido depende da confirmação do estoque inicial."/>}</Modal>;}
export function Summary({state,filters,balance=false}:{state:State;filters:Filters;balance?:boolean}) {
  const [detail,setDetail]=useState<{cat:Category;metric:keyof Monthly;month:string}|null>(null),[unit,setUnit]=useState<'KG'|'LB'>('KG');
  const metric=(cat:Category,r:Monthly,key:keyof Monthly)=>{const n=r[key] as number|null;return <button className={'number-link '+(n!==null&&n<0?'negative':'')} title="Ver composição" onClick={()=>setDetail({cat,metric:key,month:r.month})}>{fmt(n===null?null:unit==='LB'?monthlyLb(r,key as MonthlyMetric):n)}</button>;};
  return <><div className="report-hint"><p>Os saldos consideram todo o histórico confirmado. Clique em um valor para ver a composição.</p><div className="segmented"><button className={unit==='KG'?'active':''} onClick={()=>setUnit('KG')}>KG</button><button className={unit==='LB'?'active':''} onClick={()=>setUnit('LB')}>LB</button></div></div>{CATEGORIES.filter(c=>!filters.category||filters.category===c).map(cat=><section className="panel" key={cat}><div className="section-heading"><h2><span className={'product-dot '+cat}/>{CATEGORY_LABEL[cat]}</h2><span className="muted">{filters.year} · {unit}</span></div><div className="table-scroll"><table><thead><tr><th>Mês</th>{(balance?['Entradas','Saídas','Balanço do mês']:['Estoque inicial','Entradas','Atacado','Sites','Perdas','Ajustes','Estoque final']).map(label=><th className="numeric" key={label}>{label} <small>{unit}</small></th>)}</tr></thead><tbody>{monthly(state,cat,filters.year).filter(r=>!filters.month||r.month.slice(5)===filters.month).map(r=><tr key={r.month}><td><strong>{MONTHS[Number(r.month.slice(5))-1]}</strong>{r.partial&&<small>Contagem dentro do mês</small>}</td>{balance?<><td className="numeric">{r.balanceOriginal?fmt(unit==='LB'?r.balanceOriginal.entriesLb:r.balanceOriginal.entries):metric(cat,r,'entries')}</td><td className="numeric">{fmt(r.balanceOriginal?(unit==='LB'?r.balanceOriginal.outgoingLb:r.balanceOriginal.outgoing):(r.wholesale+r.sites+r.losses)*(unit==='LB'?lb(1):1))}</td><td className="numeric">{fmt(r.balanceOriginal?(unit==='LB'?r.balanceOriginal.balanceLb:r.balanceOriginal.balance):(r.entries-r.wholesale-r.sites-r.losses)*(unit==='LB'?lb(1):1))}</td></>:(['opening','entries','wholesale','sites','losses','adjustments','closing'] as (keyof Monthly)[]).map(k=><td key={k} className={'numeric '+(k==='closing'?'closing-cell':'')}>{metric(cat,r,k)}</td>)}</tr>)}</tbody></table></div></section>)}{detail&&<Composition state={state} detail={detail} onClose={()=>setDetail(null)}/>}</>;
}
export function Florida({state,filters,onOrigin}:{state:State;filters:Filters;onOrigin:(m:Movement)=>void}) {
  const rows=filtered(state.movements.filter(m=>m.status==='accepted'),filters);
  return <><HistoricalWorkbook state={state} sheetFilter="FL Qty"/><div className="info-box">Para novos dados, somente o estado de entrega FL ou Florida. O peso é calculado por quantidade × gramatura; itens sem gramatura são sinalizados.</div>{CATEGORIES.filter(c=>!filters.category||filters.category===c).map(cat=>{const grouped=floridaRows(rows,cat),sizes=[...new Set(['500g','250g','100g','5g','10g','20g','50g','10g - Haux','20g - Haux',...grouped.flatMap(r=>Object.keys(r.units))])];return <section className="panel" key={cat}><div className="section-heading"><h2><span className={'product-dot '+cat}/>{CATEGORY_LABEL[cat]} · Flórida</h2><span className="muted">Quantidades em unidades</span></div>{grouped.length?<div className="table-scroll"><table><thead><tr><th>Data</th>{sizes.map(s=><th key={s} className="numeric">{s}</th>)}<th>KG</th><th>LB</th><th>Conferência</th></tr></thead><tbody>{grouped.map(r=><tr key={r.date}><td>{r.date}</td>{sizes.map(s=><td key={s} className="numeric">{r.units[s]||'—'}</td>)}<td className="numeric">{fmt(r.kg)}</td><td className="numeric">{fmt(lb(r.kg))}</td><td>{r.missing>0&&<span className="badge pending">{r.missing} sem gramatura</span>}{r.records.map(m=><button key={m.id} className="text-link block" onClick={()=>onOrigin(m)}>{m.invoice||m.order}</button>)}</td></tr>)}</tbody></table></div>:<Empty title="Nenhuma venda na Flórida" description="As vendas confirmadas com estado de entrega identificado aparecerão aqui."/>}</section>;})}</>;
}
