'use client';
import { useEffect, useRef } from 'react';
import { X, FileSearch, Download, Inbox } from 'lucide-react';
import { CATEGORY_LABEL, KIND_LABEL, type Movement, type State } from '@/lib/model';
import { normalizeState } from '@/lib/shipping';
import { fmt, lb, movementLb } from '@/lib/domain';
export type Act=(payload:Record<string,unknown>)=>Promise<void>;
export function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);
  return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Fechar"><X size={21}/></button></div><div className="modal-body">{children}</div></dialog>;
}
export function Empty({title,description,action}:{title:string;description:string;action?:React.ReactNode}) {return <div className="empty"><span className="empty-icon"><Inbox size={28}/></span><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function Status({value}:{value:string}) {const labels:Record<string,string>={staged:'Em análise',pending:'Pendente',accepted:'Confirmado',ignored:'Ignorado',duplicate:'Conciliado'};return <span className={'badge '+value}>{labels[value]||value}</span>;}
export function SourceDetail({m,state,onClose}:{m:Movement;state:State;onClose:()=>void}) {return <Modal title="Origem do registro" onClose={onClose}><div className="detail-grid"><div><small>Produto</small><strong>{m.category?CATEGORY_LABEL[m.category]:'Não classificado'}</strong></div><div><small>Movimentação</small><strong>{KIND_LABEL[m.kind]}</strong></div><div><small>Invoice / pedido</small><strong>{m.invoice||m.order||'Não identificado'}</strong></div><div><small>Peso</small><strong>{fmt(m.kg)} KG · {fmt(movementLb(m))} LB</strong></div></div>{m.origins.map((o,i)=>{const d=state.documents.find(d=>d.id===o.documentId);return <div className="source-box" key={i}><FileSearch size={20}/><div><strong>{o.file}</strong><p>{o.sheet&&`Aba: ${o.sheet} · `}{o.row&&`Linha ${o.row}`}{o.page&&`Página ${o.page}`}</p><small>Fonte: {o.source} · Importado em {new Date(m.importedAt).toLocaleString('pt-BR')}</small>{d&&<><code>SHA-256: {d.hash}</code><a className="text-link" href={`/api/documents/${d.id}`}><Download size={15}/> Baixar original</a></>}</div></div>;})}{!m.origins.length&&<p>Informado manualmente. Motivo: {m.note}</p>}{m.note&&<details><summary>Texto extraído / observações</summary><pre className="extracted">{m.note}</pre></details>}<details><summary>Histórico de alterações</summary>{state.audit.filter(a=>a.target===m.id).map(a=><div className="audit-line" key={a.id}><strong>{a.action}</strong><p>{a.reason}</p><small>{new Date(a.at).toLocaleString('pt-BR')}</small></div>)}</details><small className="muted">Identificador: {m.id}</small></Modal>;}
export function MovementRows({rows,onOrigin,onEdit,entry=false}:{rows:Movement[];onOrigin:(m:Movement)=>void;onEdit?:(m:Movement)=>void;entry?:boolean}) {return <div className="table-scroll"><table><thead><tr><th>Data</th><th>Invoice / pedido</th><th>Cliente / destinatário</th><th>Estado</th><th>Canal</th>{entry&&<><th>Transporte</th><th>Cargo/Courier</th><th>Origem</th></>}<th className="numeric">KG</th><th className="numeric">LB</th><th>Origem</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{m.date?m.date.split('-').reverse().join('/'):'—'}</td><td><button className="text-link" onClick={()=>onEdit&&!m.historical?onEdit(m):onOrigin(m)}>{m.invoice||m.order||'Não identificado'}</button></td><td><strong>{m.customer||m.recipient||'Não identificado'}</strong>{m.customer&&m.recipient&&m.customer!==m.recipient&&<small>{m.recipient}</small>}</td><td>{normalizeState(m.state,m.shippingCountry)}</td><td>{m.site||KIND_LABEL[m.kind]}</td>{entry&&<><td>{m.transport||'—'}</td><td>{m.cargo||'—'}</td><td>{m.country||'—'}</td></>}<td className="numeric">{fmt(m.kg)}</td><td className="numeric muted">{fmt(movementLb(m))}</td><td><button className="icon-button" aria-label={`Ver origem ${m.invoice||m.id}`} onClick={()=>onOrigin(m)}><FileSearch size={18}/></button></td></tr>)}</tbody></table></div>;}
