'use client';
import { useCallback, useEffect, useState } from 'react';
import { LayoutDashboard, Upload, ArrowUpRight, ArrowDownLeft, Scale, MapPin, CalendarRange, CircleAlert, Package, Plug, Settings as SettingsIcon, Download, ChevronDown, Menu, X, LogOut, LoaderCircle, CheckCircle2, Plus, ShieldCheck } from 'lucide-react';
import { completeness, monthly } from '@/lib/domain';
import { historyComparisons } from '@/lib/history';
import { CATEGORIES, type Movement, type State } from '@/lib/model';
import { defaultFilters, type Filters } from '@/lib/reports';
import Importer from './importer';
import Review,{EditMovement} from './review';
import { Dashboard, FilterBar, Ledger, Summary, Florida } from './report-views';
import { Products, Sources, Settings } from './settings';
import { Empty, SourceDetail } from './shared';
import HistoricalWorkbook from './historical-workbook';
import FullValidation from './validation';
type View='history'|'dashboard'|'import'|'outgoing'|'incoming'|'balance'|'florida'|'summary'|'review'|'products'|'sources'|'settings';
const nav:{id:View;label:string;icon:typeof Upload;group?:string}[]=[
  {id:'history',label:'Histórico original',icon:CalendarRange},{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'import',label:'Importar arquivos',icon:Upload},
  {id:'outgoing',label:'Saídas',icon:ArrowUpRight,group:'MOVIMENTAÇÕES'},{id:'incoming',label:'Entradas',icon:ArrowDownLeft},{id:'balance',label:'Balanço',icon:Scale},{id:'florida',label:'Vendas Flórida',icon:MapPin},{id:'summary',label:'Resumo mensal',icon:CalendarRange},
  {id:'review',label:'Revisar dados',icon:CircleAlert,group:'CONFERÊNCIA'},{id:'products',label:'Produtos',icon:Package},{id:'sources',label:'Fontes de dados',icon:Plug},{id:'settings',label:'Configurações',icon:SettingsIcon}
];
const headings:Record<View,[string,string]>={history:['Histórico original','Valores da planilha preservados e aceitos como corretos.'],dashboard:['Visão geral','Seu estoque e suas movimentações, com origem em cada número.'],import:['Importar dados para análise','Reúna os documentos e prepare uma base confiável para seus relatórios.'],outgoing:['Saídas','Vendas de atacado, sites e perdas, separadas por produto.'],incoming:['Entradas','Invoices e Entry Summaries vinculados à mesma movimentação.'],balance:['Balanço mensal','Acompanhe as entradas e saídas de cada produto.'],florida:['Vendas na Flórida','Confira as vendas por data, gramatura e endereço de entrega.'],summary:['Resumo mensal de estoque','Do saldo inicial ao fechamento, com rastreabilidade.'],review:['Revisar dados','Confira as pendências antes de incluir os registros nos cálculos.'],products:['Produtos e gramaturas','Um cadastro consistente para classificar as próximas importações.'],sources:['Fontes de dados','Organize a origem de cada documento e relatório.'],settings:['Configurações','Regras de classificação, armazenamento e histórico de alterações.']};
export default function Workspace() {
  const [state,setState]=useState<State|null>(null),[view,setView]=useState<View>('import'),[filters,setFilters]=useState<Filters>(defaultFilters),[error,setError]=useState(''),[toast,setToast]=useState(''),[auth,setAuth]=useState(false),[password,setPassword]=useState(''),[mobile,setMobile]=useState(false),[origin,setOrigin]=useState<Movement|null>(null),[edit,setEdit]=useState<Movement|null>(null),[loading,setLoading]=useState(true);
  const reload=useCallback(async()=>{try{const r=await fetch('/api/state');const data=await r.json();if(r.status===401){setAuth(true);return;}if(!r.ok)throw new Error(data.error);setState(data);setAuth(false);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
  useEffect(()=>{void reload();const hash=location.hash.slice(1) as View;if(nav.some(n=>n.id===hash))setView(hash);},[reload]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(timer);},[toast]);
  const navigate=useCallback((v:View)=>{setView(v);setMobile(false);location.hash=v;},[]);
  // Optional browser agent tools use the same read state and navigation as the interface.
  useEffect(()=>{
    const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void}}).modelContext;
    if(!context)return;const lifecycle=new AbortController();
    try{context.registerTool({name:'hf_read_import_status',description:'Read received sources and pending review counts; no changes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No parameters expected');const r=await fetch('/api/state');if(!r.ok)throw new Error('Authentication required');const s:State=await r.json();return {documents:s.documents.map(d=>({name:d.name,source:d.source})),pending:s.movements.filter(m=>m.status==='pending').length,initialized:s.initialized};}},{signal:lifecycle.signal});context.registerTool({name:'hf_open_import',description:'Open the file import screen; does not upload or process files.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No parameters expected');navigate('import');return {screen:'import'};}},{signal:lifecycle.signal});}catch{/* Unsupported experimental browser API does not affect the UI. */}
    return()=>lifecycle.abort();
  },[navigate]);
  async function act(payload:Record<string,unknown>){const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,version:state?.version})});const data=await r.json();if(!r.ok){setError(data.error);throw new Error(data.error);}setState(data);setToast(payload.action==='validate_all'?'Verificação completa concluída. Consulte os resultados.':'Alteração salva. Os relatórios foram atualizados.');}
  async function download(report:string,format='xlsx'){try{const params=new URLSearchParams({...Object.fromEntries(Object.entries(filters).map(([k,v])=>[k,String(v)])),report,format});const r=await fetch('/api/export?'+params);if(!r.ok)throw new Error((await r.json()).error);const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`HF-${report}-${filters.year}.${format}`;a.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message);}}
  if(auth)return <div className="login"><div className="login-card"><div className="brand-mark">H<span>&</span>F</div><span className="eyebrow">CONTROLE DE ESTOQUE</span><h1>Acesse seu espaço</h1><p>Documentos, movimentações e relatórios da H&F.</p><form onSubmit={async e=>{e.preventDefault();setError('');const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)setError(d.error);else await reload();}}><label className="field-label">Senha de acesso<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error-box">{error}</p>}<button className="primary full">Entrar</button></form><small><ShieldCheck size={15}/> Documentos protegidos. Acesso restrito.</small></div></div>;
  if(!state)return <div className="loading-screen"><div className="brand-mark">H<span>&</span>F</div>{loading?<><LoaderCircle className="spin"/><p>Preparando seu espaço…</p></>:<><p role="alert">{error||'Não foi possível carregar os dados.'}</p><button className="primary" onClick={()=>void reload()}>Tentar novamente</button></>}</div>;
  const pending=state.movements.filter(m=>['staged','pending'].includes(m.status)).length;
  const incomplete=completeness(state).length>0||historyComparisons(state).some(c=>c.status==='Pendente')||CATEGORIES.some(c=>monthly(state,c,filters.year).some(r=>!r.historical&&r.closing!==null&&r.closing<0));
  const reporting=['dashboard','outgoing','incoming','balance','florida','summary'].includes(view),advanced=['outgoing','incoming','florida'].includes(view),exportable=['outgoing','incoming','balance','florida','summary','review'].includes(view);
  return <div className="app"><aside className={'sidebar '+(mobile?'open':'')}><a className="brand" href="#import" onClick={()=>navigate('import')}><span className="brand-mark">H<span>&</span>F</span><span>TRADING COMPANY<small>Controle de estoque</small></span></a><button className="mobile-close icon-button" onClick={()=>setMobile(false)} aria-label="Fechar menu"><X/></button><div className="workspace-label"><span className="workspace-avatar">HF</span><div>H&F USA<small>Dry Snuff & Mapacho</small></div><ChevronDown size={15}/></div><nav>{nav.map(n=><div key={n.id}>{n.group&&<p className="nav-group">{n.group}</p>}<button className={'nav-item '+(view===n.id?'active':'')} onClick={()=>navigate(n.id)}><n.icon size={18}/><span>{n.label}{['outgoing','incoming'].includes(n.id)?` ${filters.year}`:''}</span>{n.id==='review'&&pending>0&&<b>{pending}</b>}</button></div>)}</nav><div className="sidebar-bottom"><span className="tiny-monogram">HF</span><div>H&F Trading Company<small>Gestão de movimentações</small></div></div></aside>{mobile&&<div className="mobile-overlay" onClick={()=>setMobile(false)}/>}
  <div className="main-shell"><header className="topbar"><div><button className="icon-button menu-button" aria-label="Abrir menu" onClick={()=>setMobile(true)}><Menu size={21}/></button><span className="breadcrumb">Workspace <span>/</span> <strong>{nav.find(n=>n.id===view)?.label}</strong></span></div><div className="topbar-right"><label className="year-select"><CalendarRange size={16}/><select aria-label="Ano" value={filters.year} onChange={e=>setFilters({...filters,year:Number(e.target.value)})}>{Array.from(new Set([2025,2026,2027,...state.movements.map(m=>Number(m.date.slice(0,4))).filter(Boolean)])).sort().map(y=><option key={y}>{y}</option>)}</select></label><span className="user-avatar">HF</span></div></header>
  <main><div className="page-heading"><div><span className="eyebrow">H&F · CONTROLE E CONCILIAÇÃO</span><h1>{headings[view][0]}{['incoming','outgoing'].includes(view)?` ${filters.year}`:''}</h1><p>{headings[view][1]}</p></div><div className="page-actions"><FullValidation state={state} act={act} onReview={()=>navigate('review')} onEdit={setEdit}/>{view!=='import'&&<button className="secondary" onClick={()=>navigate('import')}><Plus size={17}/> Adicionar arquivos</button>}</div></div>
  {state.initialized&&incomplete&&<div className="incomplete-banner"><CircleAlert size={19}/><div><strong>DADOS INCOMPLETOS</strong><span>Há fontes ausentes, saldos a confirmar ou registros que precisam de revisão.</span></div><button onClick={()=>navigate('review')}>Ver pendências</button></div>}
  {reporting&&!state.initialized?<section className="panel"><Empty title="Primeiro, prepare sua base" description="Envie os arquivos ou marque as fontes não disponíveis. Confira o checklist antes de gerar os relatórios." action={<button className="primary" onClick={()=>navigate('import')}>Importar dados para análise</button>}/></section>:<>
  {exportable&&<div className="export-toolbar"><p>{view==='review'?'Conferência e rastreabilidade':'Somente movimentações confirmadas'}</p><div><button className="small-button" disabled={!state.initialized} onClick={()=>void download(view,'csv')}>CSV</button><button className="small-button" disabled={!state.initialized} onClick={()=>void download(view)}><Download size={15}/> Excel</button><button className="secondary" disabled={!state.initialized} onClick={()=>void download('all')}><Download size={16}/> Relatório completo</button></div></div>}
  {['incoming','outgoing','summary','balance','florida'].includes(view)&&<FilterBar filters={filters} setFilters={setFilters} advanced={advanced}/>}
  {view==='import'&&<Importer state={state} act={act} reload={reload} onReview={()=>navigate('review')} notify={setToast}/>}
  {view==='dashboard'&&<Dashboard state={state} year={filters.year} onImport={()=>navigate('import')} onReview={()=>navigate('review')}/>}
  {(view==='outgoing'||view==='incoming')&&<Ledger state={state} filters={filters} entry={view==='incoming'} onOrigin={setOrigin} onEdit={setEdit}/>}
  {(view==='summary'||view==='balance')&&<Summary state={state} filters={filters} balance={view==='balance'}/>}
  {view==='florida'&&<Florida state={state} filters={filters} onOrigin={setOrigin}/>}
  {view==='review'&&<Review state={state} act={act} onOrigin={setOrigin} onEdit={setEdit}/>}
  {view==='history'&&<HistoricalWorkbook state={state}/>}
  {view==='products'&&<Products state={state} act={act}/>}
  {view==='sources'&&<Sources onImport={()=>navigate('import')}/>}
  {view==='settings'&&<Settings state={state} act={act}/>}
  </>}
  <footer className="page-footer"><span>H&F Trading Company</span><span>KG como referência · Dry Snuff e Mapacho sempre separados</span><span>{state.storage==='postgres'?'Armazenamento online':'Versão local'}</span></footer></main></div>
  {toast&&<div className="toast" role="status"><CheckCircle2 size={20}/>{toast}<button className="icon-button" onClick={()=>setToast('')} aria-label="Fechar aviso"><X size={16}/></button></div>}
  {error&&<div className="toast error" role="alert"><CircleAlert size={20}/>{error}<button className="icon-button" onClick={()=>setError('')} aria-label="Fechar erro"><X size={16}/></button></div>}
  {origin&&<SourceDetail m={origin} state={state} onClose={()=>setOrigin(null)}/>}{edit&&<EditMovement m={edit} state={state} act={act} onClose={()=>setEdit(null)}/>}
  </div>;
}
