import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3000');
await page.getByRole('heading',{name:'Importar dados para análise'}).waitFor();
await mkdir('artifacts',{recursive:true});
await page.screenshot({path:'artifacts/import-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Resumo mensal',exact:true}).click();
await page.getByRole('heading',{name:'Primeiro, prepare sua base'}).waitFor();
await page.getByRole('button',{name:'Produtos',exact:true}).click();
await page.getByRole('button',{name:'Cadastrar produto',exact:true}).click();
await page.getByRole('dialog').waitFor();
await page.getByRole('button',{name:'Fechar',exact:true}).click();
await page.getByRole('button',{name:'Configurações',exact:true}).click();
await page.getByRole('heading',{name:'Armazenamento e acesso'}).waitFor();
await page.getByRole('button',{name:'Importar arquivos',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/import-mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
if(overflow)throw new Error('Horizontal overflow on mobile');
await page.getByRole('button',{name:'Abrir menu'}).click();
await page.getByRole('button',{name:'Fontes de dados',exact:true}).click();
await page.getByRole('heading',{name:'Upload manual',exact:true}).waitFor();
if(errors.length)throw new Error(errors.join('\n'));
console.log('PASS: desktop, mobile, onboarding gate, navigation, modal, no browser errors');
await browser.close();
